#############################################################################
# Makefile for building: CT_IOT
# Generated by qmake (3.1) (Qt 5.12.9)
# Project:  CT_IOT.pro
# Template: subdirs
# Command: E:\QT5.12.9\5.12.9\mingw73_64\bin\qmake.exe -o Makefile CT_IOT.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = E:\QT5.12.9\5.12.9\mingw73_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = E:\QT5.12.9\5.12.9\mingw73_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = E:\QT5.12.9\5.12.9\mingw73_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-IOT_Platform \
		sub-MQTT_Client \
		sub-RunTime


sub-IOT_Platform-qmake_all:  FORCE
	@if not exist IOT_Platform\ mkdir IOT_Platform\ & if not exist IOT_Platform\ exit 1
	cd IOT_Platform\ && $(QMAKE) -o Makefile D:\ct_share\CT_IOT\CT_IOT\IOT_Platform\IOT_Platform.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
	cd IOT_Platform\ && $(MAKE) -f Makefile qmake_all
sub-IOT_Platform: FORCE
	@if not exist IOT_Platform\ mkdir IOT_Platform\ & if not exist IOT_Platform\ exit 1
	cd IOT_Platform\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\ct_share\CT_IOT\CT_IOT\IOT_Platform\IOT_Platform.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-IOT_Platform-make_first: FORCE
	@if not exist IOT_Platform\ mkdir IOT_Platform\ & if not exist IOT_Platform\ exit 1
	cd IOT_Platform\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\ct_share\CT_IOT\CT_IOT\IOT_Platform\IOT_Platform.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-IOT_Platform-all: FORCE
	@if not exist IOT_Platform\ mkdir IOT_Platform\ & if not exist IOT_Platform\ exit 1
	cd IOT_Platform\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\ct_share\CT_IOT\CT_IOT\IOT_Platform\IOT_Platform.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-IOT_Platform-clean: FORCE
	@if not exist IOT_Platform\ mkdir IOT_Platform\ & if not exist IOT_Platform\ exit 1
	cd IOT_Platform\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\ct_share\CT_IOT\CT_IOT\IOT_Platform\IOT_Platform.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-IOT_Platform-distclean: FORCE
	@if not exist IOT_Platform\ mkdir IOT_Platform\ & if not exist IOT_Platform\ exit 1
	cd IOT_Platform\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\ct_share\CT_IOT\CT_IOT\IOT_Platform\IOT_Platform.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-IOT_Platform-install_subtargets: FORCE
	@if not exist IOT_Platform\ mkdir IOT_Platform\ & if not exist IOT_Platform\ exit 1
	cd IOT_Platform\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\ct_share\CT_IOT\CT_IOT\IOT_Platform\IOT_Platform.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-IOT_Platform-uninstall_subtargets: FORCE
	@if not exist IOT_Platform\ mkdir IOT_Platform\ & if not exist IOT_Platform\ exit 1
	cd IOT_Platform\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\ct_share\CT_IOT\CT_IOT\IOT_Platform\IOT_Platform.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-MQTT_Client-qmake_all:  FORCE
	@if not exist MQTT_Client\ mkdir MQTT_Client\ & if not exist MQTT_Client\ exit 1
	cd MQTT_Client\ && $(QMAKE) -o Makefile D:\ct_share\CT_IOT\CT_IOT\MQTT_Client\MQTT_Client.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
	cd MQTT_Client\ && $(MAKE) -f Makefile qmake_all
sub-MQTT_Client: FORCE
	@if not exist MQTT_Client\ mkdir MQTT_Client\ & if not exist MQTT_Client\ exit 1
	cd MQTT_Client\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\ct_share\CT_IOT\CT_IOT\MQTT_Client\MQTT_Client.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-MQTT_Client-make_first: FORCE
	@if not exist MQTT_Client\ mkdir MQTT_Client\ & if not exist MQTT_Client\ exit 1
	cd MQTT_Client\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\ct_share\CT_IOT\CT_IOT\MQTT_Client\MQTT_Client.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-MQTT_Client-all: FORCE
	@if not exist MQTT_Client\ mkdir MQTT_Client\ & if not exist MQTT_Client\ exit 1
	cd MQTT_Client\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\ct_share\CT_IOT\CT_IOT\MQTT_Client\MQTT_Client.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-MQTT_Client-clean: FORCE
	@if not exist MQTT_Client\ mkdir MQTT_Client\ & if not exist MQTT_Client\ exit 1
	cd MQTT_Client\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\ct_share\CT_IOT\CT_IOT\MQTT_Client\MQTT_Client.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-MQTT_Client-distclean: FORCE
	@if not exist MQTT_Client\ mkdir MQTT_Client\ & if not exist MQTT_Client\ exit 1
	cd MQTT_Client\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\ct_share\CT_IOT\CT_IOT\MQTT_Client\MQTT_Client.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-MQTT_Client-install_subtargets: FORCE
	@if not exist MQTT_Client\ mkdir MQTT_Client\ & if not exist MQTT_Client\ exit 1
	cd MQTT_Client\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\ct_share\CT_IOT\CT_IOT\MQTT_Client\MQTT_Client.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-MQTT_Client-uninstall_subtargets: FORCE
	@if not exist MQTT_Client\ mkdir MQTT_Client\ & if not exist MQTT_Client\ exit 1
	cd MQTT_Client\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\ct_share\CT_IOT\CT_IOT\MQTT_Client\MQTT_Client.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-RunTime-qmake_all:  FORCE
	@if not exist RunTime\ mkdir RunTime\ & if not exist RunTime\ exit 1
	cd RunTime\ && $(QMAKE) -o Makefile D:\ct_share\CT_IOT\CT_IOT\RunTime\RunTime.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
	cd RunTime\ && $(MAKE) -f Makefile qmake_all
sub-RunTime: FORCE
	@if not exist RunTime\ mkdir RunTime\ & if not exist RunTime\ exit 1
	cd RunTime\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\ct_share\CT_IOT\CT_IOT\RunTime\RunTime.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-RunTime-make_first: FORCE
	@if not exist RunTime\ mkdir RunTime\ & if not exist RunTime\ exit 1
	cd RunTime\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\ct_share\CT_IOT\CT_IOT\RunTime\RunTime.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-RunTime-all: FORCE
	@if not exist RunTime\ mkdir RunTime\ & if not exist RunTime\ exit 1
	cd RunTime\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\ct_share\CT_IOT\CT_IOT\RunTime\RunTime.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-RunTime-clean: FORCE
	@if not exist RunTime\ mkdir RunTime\ & if not exist RunTime\ exit 1
	cd RunTime\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\ct_share\CT_IOT\CT_IOT\RunTime\RunTime.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-RunTime-distclean: FORCE
	@if not exist RunTime\ mkdir RunTime\ & if not exist RunTime\ exit 1
	cd RunTime\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\ct_share\CT_IOT\CT_IOT\RunTime\RunTime.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-RunTime-install_subtargets: FORCE
	@if not exist RunTime\ mkdir RunTime\ & if not exist RunTime\ exit 1
	cd RunTime\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\ct_share\CT_IOT\CT_IOT\RunTime\RunTime.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-RunTime-uninstall_subtargets: FORCE
	@if not exist RunTime\ mkdir RunTime\ & if not exist RunTime\ exit 1
	cd RunTime\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\ct_share\CT_IOT\CT_IOT\RunTime\RunTime.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall

Makefile: CT_IOT.pro E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/win32-g++/qmake.conf E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/spec_pre.prf \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/qdevice.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/device_config.prf \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/common/sanitize.conf \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/common/gcc-base.conf \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/common/g++-base.conf \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/common/angle.conf \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/win32/windows_vulkan_sdk.prf \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/common/windows-vulkan.conf \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/common/g++-win32.conf \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/qconfig.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3danimation.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dcore.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dextras.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dinput.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dlogic.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquick.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3drender.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3drender_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_axbase.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_axbase_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_axcontainer.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_axcontainer_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_axserver.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_axserver_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_bluetooth.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_charts.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_charts_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_concurrent.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_core.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_core_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_datavisualization.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_dbus.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_dbus_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_designer.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_designer_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_gamepad.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_gui.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_gui_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_help.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_help_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_location.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_location_private.pri \
		../../qt-demos/qtmqtt/build-qtmqtt-Desktop_Qt_5_12_9_MinGW_64_bit-Release/mkspecs/modules-inst/qt_lib_mqtt.pri \
		../../qt-demos/qtmqtt/build-qtmqtt-Desktop_Qt_5_12_9_MinGW_64_bit-Release/mkspecs/modules-inst/qt_lib_mqtt_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_mqtt.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_multimedia.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_network.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_network_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_networkauth.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_nfc.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_nfc_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_opengl.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_opengl_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_openglextensions.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_positioning.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_positioning_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_positioningquick.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_printsupport.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_purchasing.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_qml.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_qml_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_qmltest.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_quick.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_quick_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_repparser.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_repparser_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_script.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_script_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_scripttools.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_scxml.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_scxml_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_sensors.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_sensors_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_serialbus.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_serialport.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_serialport_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_sql.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_sql_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_svg.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_svg_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_testlib.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_testlib_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_texttospeech.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_uiplugin.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_uitools.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_uitools_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_webchannel.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_websockets.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_websockets_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_widgets.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_widgets_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_winextras.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_winextras_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_xml.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_xml_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/qt_functions.prf \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/qt_config.prf \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/win32-g++/qmake.conf \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/exclusive_builds.prf \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/toolchain.prf \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/default_pre.prf \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/win32/default_pre.prf \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/resolve_config.prf \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/exclusive_builds_post.prf \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/default_post.prf \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/qml_debug.prf \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/precompile_header.prf \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/warn_on.prf \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/qmake_use.prf \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/file_copies.prf \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/win32/windows.prf \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/testcase_targets.prf \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/exceptions.prf \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/yacc.prf \
		E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/lex.prf \
		CT_IOT.pro
	$(QMAKE) -o Makefile CT_IOT.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/spec_pre.prf:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/qdevice.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/device_config.prf:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/common/sanitize.conf:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/common/gcc-base.conf:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/common/g++-base.conf:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/common/angle.conf:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/win32/windows_vulkan_sdk.prf:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/common/windows-vulkan.conf:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/common/g++-win32.conf:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/qconfig.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3danimation.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3danimation_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dcore.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dcore_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dextras.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dextras_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dinput.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dinput_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dlogic.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquick.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquick_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquickextras.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquickinput.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquickrender.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3drender.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_3drender_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_axbase.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_axbase_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_axcontainer.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_axcontainer_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_axserver.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_axserver_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_bluetooth.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_charts.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_charts_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_concurrent.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_concurrent_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_core.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_core_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_datavisualization.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_dbus.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_dbus_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_designer.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_designer_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_edid_support_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_egl_support_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_fb_support_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_gamepad.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_gamepad_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_gui.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_gui_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_help.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_help_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_location.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_location_private.pri:
../../qt-demos/qtmqtt/build-qtmqtt-Desktop_Qt_5_12_9_MinGW_64_bit-Release/mkspecs/modules-inst/qt_lib_mqtt.pri:
../../qt-demos/qtmqtt/build-qtmqtt-Desktop_Qt_5_12_9_MinGW_64_bit-Release/mkspecs/modules-inst/qt_lib_mqtt_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_mqtt.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_multimedia.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_multimedia_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_network.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_network_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_networkauth.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_networkauth_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_nfc.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_nfc_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_opengl.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_opengl_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_openglextensions.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_positioning.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_positioning_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_positioningquick.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_printsupport.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_printsupport_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_purchasing.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_purchasing_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_qml.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_qml_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_qmltest.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_qmltest_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_quick.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_quick_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_quickwidgets.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_remoteobjects.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_repparser.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_repparser_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_script.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_script_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_scripttools.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_scripttools_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_scxml.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_scxml_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_sensors.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_sensors_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_serialbus.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_serialbus_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_serialport.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_serialport_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_sql.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_sql_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_svg.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_svg_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_testlib.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_testlib_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_texttospeech.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_theme_support_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_uiplugin.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_uitools.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_uitools_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_vulkan_support_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_webchannel.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_webchannel_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_websockets.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_websockets_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_widgets.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_widgets_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_winextras.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_winextras_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_xml.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_xml_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/qt_functions.prf:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/qt_config.prf:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/win32-g++/qmake.conf:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/spec_post.prf:
.qmake.stash:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/exclusive_builds.prf:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/toolchain.prf:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/default_pre.prf:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/win32/default_pre.prf:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/resolve_config.prf:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/exclusive_builds_post.prf:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/default_post.prf:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/qml_debug.prf:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/precompile_header.prf:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/warn_on.prf:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/qmake_use.prf:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/file_copies.prf:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/win32/windows.prf:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/testcase_targets.prf:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/exceptions.prf:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/yacc.prf:
E:/QT5.12.9/5.12.9/mingw73_64/mkspecs/features/lex.prf:
CT_IOT.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile CT_IOT.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"

qmake_all: sub-IOT_Platform-qmake_all sub-MQTT_Client-qmake_all sub-RunTime-qmake_all FORCE

make_first: sub-IOT_Platform-make_first sub-MQTT_Client-make_first sub-RunTime-make_first  FORCE
all: sub-IOT_Platform-all sub-MQTT_Client-all sub-RunTime-all  FORCE
clean: sub-IOT_Platform-clean sub-MQTT_Client-clean sub-RunTime-clean  FORCE
distclean: sub-IOT_Platform-distclean sub-MQTT_Client-distclean sub-RunTime-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-IOT_Platform-install_subtargets sub-MQTT_Client-install_subtargets sub-RunTime-install_subtargets FORCE
uninstall_subtargets: sub-IOT_Platform-uninstall_subtargets sub-MQTT_Client-uninstall_subtargets sub-RunTime-uninstall_subtargets FORCE

sub-IOT_Platform-debug:
	@if not exist IOT_Platform\ mkdir IOT_Platform\ & if not exist IOT_Platform\ exit 1
	cd IOT_Platform\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\ct_share\CT_IOT\CT_IOT\IOT_Platform\IOT_Platform.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-MQTT_Client-debug:
	@if not exist MQTT_Client\ mkdir MQTT_Client\ & if not exist MQTT_Client\ exit 1
	cd MQTT_Client\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\ct_share\CT_IOT\CT_IOT\MQTT_Client\MQTT_Client.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
sub-RunTime-debug:
	@if not exist RunTime\ mkdir RunTime\ & if not exist RunTime\ exit 1
	cd RunTime\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\ct_share\CT_IOT\CT_IOT\RunTime\RunTime.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
debug: sub-IOT_Platform-debug sub-MQTT_Client-debug sub-RunTime-debug

sub-IOT_Platform-release:
	@if not exist IOT_Platform\ mkdir IOT_Platform\ & if not exist IOT_Platform\ exit 1
	cd IOT_Platform\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\ct_share\CT_IOT\CT_IOT\IOT_Platform\IOT_Platform.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-MQTT_Client-release:
	@if not exist MQTT_Client\ mkdir MQTT_Client\ & if not exist MQTT_Client\ exit 1
	cd MQTT_Client\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\ct_share\CT_IOT\CT_IOT\MQTT_Client\MQTT_Client.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
sub-RunTime-release:
	@if not exist RunTime\ mkdir RunTime\ & if not exist RunTime\ exit 1
	cd RunTime\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\ct_share\CT_IOT\CT_IOT\RunTime\RunTime.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
release: sub-IOT_Platform-release sub-MQTT_Client-release sub-RunTime-release

sub-IOT_Platform-check:
	@if not exist IOT_Platform\ mkdir IOT_Platform\ & if not exist IOT_Platform\ exit 1
	cd IOT_Platform\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\ct_share\CT_IOT\CT_IOT\IOT_Platform\IOT_Platform.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-MQTT_Client-check:
	@if not exist MQTT_Client\ mkdir MQTT_Client\ & if not exist MQTT_Client\ exit 1
	cd MQTT_Client\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\ct_share\CT_IOT\CT_IOT\MQTT_Client\MQTT_Client.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
sub-RunTime-check:
	@if not exist RunTime\ mkdir RunTime\ & if not exist RunTime\ exit 1
	cd RunTime\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\ct_share\CT_IOT\CT_IOT\RunTime\RunTime.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
check: sub-IOT_Platform-check sub-MQTT_Client-check sub-RunTime-check

sub-IOT_Platform-benchmark:
	@if not exist IOT_Platform\ mkdir IOT_Platform\ & if not exist IOT_Platform\ exit 1
	cd IOT_Platform\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\ct_share\CT_IOT\CT_IOT\IOT_Platform\IOT_Platform.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-MQTT_Client-benchmark:
	@if not exist MQTT_Client\ mkdir MQTT_Client\ & if not exist MQTT_Client\ exit 1
	cd MQTT_Client\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\ct_share\CT_IOT\CT_IOT\MQTT_Client\MQTT_Client.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
sub-RunTime-benchmark:
	@if not exist RunTime\ mkdir RunTime\ & if not exist RunTime\ exit 1
	cd RunTime\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\ct_share\CT_IOT\CT_IOT\RunTime\RunTime.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
benchmark: sub-IOT_Platform-benchmark sub-MQTT_Client-benchmark sub-RunTime-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

